float:
  cosine:
  - base_args: ['@metric']
    constructor: Puffinn
    disabled: false
    singularity_image: puffinn
    module: vibe.algorithms.puffinn
    name: puffinn
    run_groups:
      base:
        args: [[536870912, 1073741824, 2147483648, 4294967296, 8589934592], [fht_crosspolytope]]
        query_args: [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]]
  normalized:
  - base_args: ['@metric']
    constructor: Puffinn
    disabled: false
    singularity_image: puffinn
    module: vibe.algorithms.puffinn
    name: puffinn
    run_groups:
      base:
        args: [[536870912, 1073741824, 2147483648, 4294967296, 8589934592], [fht_crosspolytope]]
        query_args: [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]]
