uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: Vamana
    disabled: false
    singularity_image: diskann
    module: vibe.algorithms.diskann
    name: vamana(diskann)
    run_groups:
      diskann-64:
        args: [[64], [64, 128, 192], [1.2, 1.4, 1.6]]
        query_args: [[100, 125, 150, 200, 300, 400, 500, 600, 800, 1000]]
      diskann-128:
        args: [[128], [128, 192], [1.2, 1.4, 1.6]]
        query_args: [[100, 125, 150, 200, 300, 400, 500, 600, 800, 1000]]
float:
  any:
  - base_args: ['@metric']
    constructor: Vamana
    disabled: false
    singularity_image: diskann
    module: vibe.algorithms.diskann
    name: vamana(diskann)
    run_groups:
      diskann-64:
        args: [[64], [64, 128, 192], [1.2, 1.4, 1.6]]
        query_args: [[100, 125, 150, 200, 300, 400, 500, 600, 800, 1000]]
      diskann-128:
        args: [[128], [128, 192], [1.2, 1.4, 1.6]]
        query_args: [[100, 125, 150, 200, 300, 400, 500, 600, 800, 1000]]