binary:
  hamming:
  - base_args: ['@metric']
    constructor: ONNG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-onng
    run_groups:
      onng:
        args:
          edge: [100]
          outdegree: [64]
          indegree: [120]
          search_edge: [0]
          epsilon: [0.02, 0.04, 0.06, 0.08, 0.1]
          refine: [0]
        query_args:
        - - {epsilon: 0.6, edge_size: -2}
          - {epsilon: 0.9, edge_size: -2}
          - {epsilon: 1.0, edge_size: -2}
          - {epsilon: 1.02, edge_size: -2}
          - {epsilon: 1.03, edge_size: -2}
          - {epsilon: 1.04, edge_size: -2}
          - {epsilon: 1.05, edge_size: -2}
          - {epsilon: 1.07, edge_size: -2}
          - {epsilon: 1.1, edge_size: -2}
          - {epsilon: 1.2, edge_size: -2}
          - {epsilon: 0.995, edge_size: 40}
          - {epsilon: 0.998, edge_size: 40}
          - {epsilon: 1.0, edge_size: 40}
          - {epsilon: 1.005, edge_size: 40}
          - {epsilon: 1.01, edge_size: 40}
          - {epsilon: 1.015, edge_size: 40}
          - {epsilon: 1.02, edge_size: 40}
uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: ONNG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-onng
    run_groups:
      onng:
        args:
          edge: [100]
          outdegree: [64]
          indegree: [120]
          search_edge: [0]
          epsilon: [0.02, 0.04, 0.06, 0.08, 0.1]
          refine: [0]
        query_args:
        - - {epsilon: 0.6, edge_size: -2}
          - {epsilon: 0.9, edge_size: -2}
          - {epsilon: 1.0, edge_size: -2}
          - {epsilon: 1.02, edge_size: -2}
          - {epsilon: 1.03, edge_size: -2}
          - {epsilon: 1.04, edge_size: -2}
          - {epsilon: 1.05, edge_size: -2}
          - {epsilon: 1.07, edge_size: -2}
          - {epsilon: 1.1, edge_size: -2}
          - {epsilon: 1.2, edge_size: -2}
          - {epsilon: 0.995, edge_size: 40}
          - {epsilon: 0.998, edge_size: 40}
          - {epsilon: 1.0, edge_size: 40}
          - {epsilon: 1.005, edge_size: 40}
          - {epsilon: 1.01, edge_size: 40}
          - {epsilon: 1.015, edge_size: 40}
          - {epsilon: 1.02, edge_size: 40}
float:
  any:
  - base_args: ['@metric']
    constructor: QG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-qg
    run_groups:
      qg:
        args:
          edge: [100]
          outdegree: [64]
          indegree: [120]
          max_edge: [96]
          epsilon: [0.02, 0.04, 0.06, 0.08, 0.1]
          sample: [2000]
        query_args:
        - - {result_expansion: 0.0, epsilon: 0.9}
          - {result_expansion: 0.0, epsilon: 0.95}
          - {result_expansion: 0.0, epsilon: 0.98}
          - {result_expansion: 0.0, epsilon: 1.0}
          - {result_expansion: 1.2, epsilon: 0.9}
          - {result_expansion: 1.5, epsilon: 0.9}
          - {result_expansion: 2.0, epsilon: 0.9}
          - {result_expansion: 3.0, epsilon: 0.9}
          - {result_expansion: 1.2, epsilon: 0.95}
          - {result_expansion: 1.5, epsilon: 0.95}
          - {result_expansion: 2.0, epsilon: 0.95}
          - {result_expansion: 3.0, epsilon: 0.95}
          - {result_expansion: 1.2, epsilon: 0.98}
          - {result_expansion: 1.5, epsilon: 0.98}
          - {result_expansion: 2.0, epsilon: 0.98}
          - {result_expansion: 3.0, epsilon: 0.98}
          - {result_expansion: 1.2, epsilon: 1.0}
          - {result_expansion: 1.5, epsilon: 1.0}
          - {result_expansion: 2.0, epsilon: 1.0}
          - {result_expansion: 3.0, epsilon: 1.0}
          - {result_expansion: 5, epsilon: 1.0}
          - {result_expansion: 10, epsilon: 1.0}
          - {result_expansion: 20, epsilon: 1.0}
          - {result_expansion: 1.2, epsilon: 1.02}
          - {result_expansion: 1.5, epsilon: 1.02}
          - {result_expansion: 2.0, epsilon: 1.02}
          - {result_expansion: 3.0, epsilon: 1.02}
          - {result_expansion: 2, epsilon: 1.04}
          - {result_expansion: 3, epsilon: 1.04}
          - {result_expansion: 5, epsilon: 1.04}
          - {result_expansion: 8, epsilon: 1.04}
  - base_args: ['@metric']
    constructor: ONNG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-onng
    run_groups:
      onng:
        args:
          edge: [100]
          outdegree: [64]
          indegree: [120]
          search_edge: [0]
          epsilon: [0.02, 0.04, 0.06, 0.08, 0.1]
          refine: [0]
        query_args:
        - - {epsilon: 0.6, edge_size: -2}
          - {epsilon: 0.9, edge_size: -2}
          - {epsilon: 1.0, edge_size: -2}
          - {epsilon: 1.02, edge_size: -2}
          - {epsilon: 1.03, edge_size: -2}
          - {epsilon: 1.04, edge_size: -2}
          - {epsilon: 1.05, edge_size: -2}
          - {epsilon: 1.07, edge_size: -2}
          - {epsilon: 1.1, edge_size: -2}
          - {epsilon: 1.2, edge_size: -2}
          - {epsilon: 0.995, edge_size: 40}
          - {epsilon: 0.998, edge_size: 40}
          - {epsilon: 1.0, edge_size: 40}
          - {epsilon: 1.005, edge_size: 40}
          - {epsilon: 1.01, edge_size: 40}
          - {epsilon: 1.015, edge_size: 40}
          - {epsilon: 1.02, edge_size: 40}
