binary:
  hamming:
  - base_args: ['@metric']
    constructor: ONNG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-onng
    run_groups:
      onng:
        args: [[100], [64], [120], [0], [0.02, 0.04, 0.06, 0.08, 0.10], [0]]
        query_args: [[[0.6, -2], [0.9, -2], [1.0, -2], [1.02, -2], [1.03, -2], [1.04,
              -2], [1.05, -2], [1.07, -2], [1.1, -2], [1.2, -2], [0.995, 40],
              [0.998, 40], [1.0, 40], [1.005, 40], [1.01, 40], [1.015, 40], [1.02, 40]]]
uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: ONNG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-onng
    run_groups:
      onng:
        args: [[100], [64], [120], [0], [0.02, 0.04, 0.06, 0.08, 0.10], [0]]
        query_args: [[[0.6, -2], [0.9, -2], [1.0, -2], [1.02, -2], [1.03, -2], [1.04,
              -2], [1.05, -2], [1.07, -2], [1.1, -2], [1.2, -2], [0.995, 40],
              [0.998, 40], [1.0, 40], [1.005, 40], [1.01, 40], [1.015, 40], [1.02, 40]]]
float:
  any:
  - base_args: ['@metric']
    constructor: QG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-qg
    run_groups:
      qg:
        args: [[100], [64], [120], [96], [0.02, 0.04, 0.06, 0.08, 0.10], [2000]]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
  - base_args: ['@metric']
    constructor: ONNG
    disabled: false
    singularity_image: ngt
    module: vibe.algorithms.ngt
    name: ngt-onng
    run_groups:
      onng:
        args: [[100], [64], [120], [0], [0.02, 0.04, 0.06, 0.08, 0.10], [0]]
        query_args: [[[0.6, -2], [0.9, -2], [1.0, -2], [1.02, -2], [1.03, -2], [1.04,
              -2], [1.05, -2], [1.07, -2], [1.1, -2], [1.2, -2], [0.995, 40],
              [0.998, 40], [1.0, 40], [1.005, 40], [1.01, 40], [1.015, 40], [1.02, 40]]]