name: base
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - pytorch
channel_priority: strict
dependencies:
  - python=3.12
  - cuvs=26.04.00
  - cuda-version=12.8
  - datasets=5.0.0
  - einops=0.8.2
  - h5py=3.16.0
  - faiss-cpu=1.14.2
  - psutil=7.2.2
  - cupy
  - numba
  - numpy
  - scikit-learn
  - litellm
