uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: FlatNav
    disabled: false
    singularity_image: flatnav
    module: vibe.algorithms.flatnav
    name: flatnav
    run_groups:
      base:
        args: [[4, 8, 12, 16, 24, 36, 48, 64, 96], [500]]
        query_args: [[10, 20, 30, 40, 50, 60, 80, 100, 150, 200, 300, 400, 500, 600, 800, 1000]]
float:
  any:
  - base_args: ['@metric']
    constructor: FlatNav
    disabled: false
    singularity_image: flatnav
    module: vibe.algorithms.flatnav
    name: flatnav
    run_groups:
      base:
        args: [[4, 8, 12, 16, 24, 36, 48, 64, 96], [500]]
        query_args: [[10, 20, 30, 40, 50, 60, 80, 100, 150, 200, 300, 400, 500, 600, 800, 1000]]