float:
  any:
  - base_args: ['@metric']
    constructor: GGNN
    disabled: false
    gpu: true
    singularity_image: ggnn
    module: vibe.algorithms.ggnn
    name: ggnn
    run_groups:
      base:
        args: [[24, 48, 96], [0.3, 0.5, 0.7, 0.9]]
        query_args: [[0.7, 1.0, 1.3, 1.6, 1.9], [200, 400, 800, 1200, 1600, 2000]]