vector:
  chamfer:
  - base_args: ['@metric']
    constructor: IGPIndex
    disabled: false
    singularity_image: igp
    module: vibe.algorithms.igp
    name: igp
    run_groups:
      base:
        args: [[2048, 4096, 8192], [2, 8]]
        query_args: [[1, 2, 4, 8, 16, 32], [100, 200, 500, 700, 1000]]
