uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: cuVSIVF
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivf
    run_groups:
      base-512:
        args:
          n_lists: [512]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64]
      base-1024:
        args:
          n_lists: [1024]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128]
      base-2048:
        args:
          n_lists: [2048]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256]
      base-4096:
        args:
          n_lists: [4096]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
      base-8192:
        args:
          n_lists: [8192]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  - base_args: ['@metric']
    constructor: cuVSIVFPQ
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivfpq
    run_groups:
      base-512:
        args:
          n_lists: [512]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64]
          refine_ratio: [1, 2, 4]
      base-1024:
        args:
          n_lists: [1024]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128]
          refine_ratio: [1, 2, 4]
      base-2048:
        args:
          n_lists: [2048]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256]
          refine_ratio: [1, 2, 4]
      base-4096:
        args:
          n_lists: [4096]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
          refine_ratio: [1, 2, 4]
  - base_args: ['@metric']
    constructor: cuVSCAGRA
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-cagra
    run_groups:
      base:
        args:
          graph_degree: [4, 8, 16, 32, 64, 128]
          intermediate_graph_degree: [4, 8, 16, 32, 64, 128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
float:
  any:
  - base_args: ['@metric']
    constructor: cuVSIVF
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivf
    run_groups:
      base-512:
        args:
          n_lists: [512]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64]
      base-1024:
        args:
          n_lists: [1024]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128]
      base-2048:
        args:
          n_lists: [2048]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256]
      base-4096:
        args:
          n_lists: [4096]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
      base-8192:
        args:
          n_lists: [8192]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  - base_args: ['@metric']
    constructor: cuVSIVFPQ
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivfpq
    run_groups:
      base-512:
        args:
          n_lists: [512]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64]
          refine_ratio: [1, 2, 4]
      base-1024:
        args:
          n_lists: [1024]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128]
          refine_ratio: [1, 2, 4]
      base-2048:
        args:
          n_lists: [2048]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256]
          refine_ratio: [1, 2, 4]
      base-4096:
        args:
          n_lists: [4096]
          pq_dim: [0]
          pq_bits: [8, 6, 4]
        query_args:
          n_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
          refine_ratio: [1, 2, 4]
  - base_args: ['@metric']
    constructor: cuVSCAGRA
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-cagra
    run_groups:
      degree-4:
        args:
          graph_degree: [4]
          intermediate_graph_degree: [4, 8, 16, 32, 64, 128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
      degree-8:
        args:
          graph_degree: [8]
          intermediate_graph_degree: [8, 16, 32, 64, 128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
      degree-16:
        args:
          graph_degree: [16]
          intermediate_graph_degree: [16, 32, 64, 128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
      degree-32:
        args:
          graph_degree: [32]
          intermediate_graph_degree: [32, 64, 128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
      degree-64:
        args:
          graph_degree: [64]
          intermediate_graph_degree: [64, 128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
      degree-128:
        args:
          graph_degree: [128]
          intermediate_graph_degree: [128]
        query_args:
          itopk: [128, 256, 384, 512]
          search_width: [1, 2, 4, 8, 16, 32, 64]
