uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: cuVSIVF
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivf
    run_groups:
      base:
        args: [[512, 1024, 2048, 4096, 8192, 16384]]
        query_args: [[1, 5, 10, 50, 100, 200, 500, 1000]]
  - base_args: ['@metric']
    constructor: cuVSIVFPQ
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivfpq
    run_groups:
      base:
        args: [[1024, 2048, 4096, 8192], [0], [8, 6, 4]]
        query_args: [[1, 5, 10, 50, 100, 200], [16, 32], [1, 2, 4]]
  - base_args: ['@metric']
    constructor: cuVSCAGRA
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-cagra
    run_groups:
      base:
        args: [[4, 8, 16, 32, 64, 128], [4, 8, 16, 32, 64, 128]]
        query_args: [[128, 256, 384, 512], [1, 2, 4, 8, 16, 32, 64]]
float:
  any:
  - base_args: ['@metric']
    constructor: cuVSIVF
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivf
    run_groups:
      base:
        args: [[512, 1024, 2048, 4096, 8192, 16384]]
        query_args: [[1, 5, 10, 50, 100, 200, 500, 1000]]
  - base_args: ['@metric']
    constructor: cuVSIVFPQ
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-ivfpq
    run_groups:
      base:
        args: [[1024, 2048, 4096, 8192], [0], [8, 6, 4]]
        query_args: [[1, 5, 10, 50, 100, 200], [16, 32], [1, 2, 4]]
  - base_args: ['@metric']
    constructor: cuVSCAGRA
    disabled: false
    gpu: true
    singularity_image: cuvs
    module: vibe.algorithms.cuvs
    name: cuvs-cagra
    run_groups:
      base:
        args: [[4, 8, 16, 32, 64, 128], [4, 8, 16, 32, 64, 128]]
        query_args: [[128, 256, 384, 512], [1, 2, 4, 8, 16, 32, 64]]