vector:
  chamfer:
  - base_args: ['@metric']
    constructor: DESSERT
    disabled: false
    singularity_image: dessert
    module: vibe.algorithms.dessert
    name: dessert
    run_groups:
      base:
        args: [[16, 32, 64], [4, 6], [512, 1024, 2048, 4096]]
        query_args: [[1, 2, 4], [128, 256, 512, 1024, 2048, 4096, 8192, 16348]]
