float:
  any:
  - base_args: ['@metric']
    constructor: FalconnPP
    disabled: false
    singularity_image: falconnpp
    module: vibe.algorithms.falconnpp
    name: falconnpp
    run_groups:
      falconnpp:
        args:
          numTables: [10, 50, 100, 200]
          numProj: [512]
          bucketLimit: [50, 100]
          alpha: [0.01, 0.001]
          iProbes: [3]
        query_args:
          qProbes: [1000, 2000, 4000, 8000, 10000, 12000, 14000, 16000]
