float:
  any:
  - base_args: ['@metric']
    constructor: FalconnPP
    disabled: false
    singularity_image: falconnpp
    module: vibe.algorithms.falconnpp
    name: falconnpp
    run_groups:
      falconnpp:
        args: [[10, 50, 100, 200], [512], [50, 100], [0.01, 0.001], [3]]
        query_args: [[1000, 2000, 4000, 8000, 10000, 12000, 14000, 16000]]