float:
  any:
  - base_args: ['@metric']
    constructor: LorannGPU
    disabled: true
    gpu: true
    singularity_image: lorann_gpu
    module: vibe.algorithms.lorann_gpu
    name: lorann-gpu
    run_groups:
      lorann:
        args: [[64, 128, 192], [24], [5], [1024, 2048, 4096], [16, 32]]
        query_args: [[8, 16, 24, 32, 48, 64, 96, 128, 256], [100, 200, 400, 800, 1200, 1600, 2400, 3200]]