float:
  any:
  - base_args: ['@metric']
    constructor: LorannGPU
    disabled: true
    gpu: true
    ood: true
    singularity_image: lorann_gpu
    module: vibe.algorithms.lorann_gpu
    name: lorann-gpu
    run_groups:
      lorann:
        args:
          global_dim: [128, 256, 384]
          rank: [24]
          train_size: [5]
          n_clusters: [1024, 2048]
          precision: [16, 32]
        query_args:
        - - {clusters_to_search: 8, points_to_rerank: 100}
          - {clusters_to_search: 8, points_to_rerank: 200}
          - {clusters_to_search: 8, points_to_rerank: 400}
          - {clusters_to_search: 8, points_to_rerank: 800}
          - {clusters_to_search: 16, points_to_rerank: 100}
          - {clusters_to_search: 16, points_to_rerank: 200}
          - {clusters_to_search: 16, points_to_rerank: 400}
          - {clusters_to_search: 16, points_to_rerank: 800}
          - {clusters_to_search: 24, points_to_rerank: 400}
          - {clusters_to_search: 24, points_to_rerank: 800}
          - {clusters_to_search: 24, points_to_rerank: 1200}
          - {clusters_to_search: 24, points_to_rerank: 1600}
          - {clusters_to_search: 32, points_to_rerank: 400}
          - {clusters_to_search: 32, points_to_rerank: 800}
          - {clusters_to_search: 32, points_to_rerank: 1200}
          - {clusters_to_search: 32, points_to_rerank: 1600}
          - {clusters_to_search: 48, points_to_rerank: 800}
          - {clusters_to_search: 48, points_to_rerank: 1200}
          - {clusters_to_search: 48, points_to_rerank: 1600}
          - {clusters_to_search: 48, points_to_rerank: 2400}
          - {clusters_to_search: 64, points_to_rerank: 1200}
          - {clusters_to_search: 64, points_to_rerank: 1600}
          - {clusters_to_search: 64, points_to_rerank: 2400}
          - {clusters_to_search: 64, points_to_rerank: 3200}
          - {clusters_to_search: 128, points_to_rerank: 1200}
          - {clusters_to_search: 128, points_to_rerank: 1600}
          - {clusters_to_search: 128, points_to_rerank: 2400}
          - {clusters_to_search: 128, points_to_rerank: 3200}
          - {clusters_to_search: 256, points_to_rerank: 2400}
          - {clusters_to_search: 256, points_to_rerank: 3200}
          - {clusters_to_search: 256, points_to_rerank: 4000}
          - {clusters_to_search: 256, points_to_rerank: 4800}
