vector:
  chamfer:
  - base_args: ['@metric']
    constructor: MUVERA
    disabled: false
    singularity_image: muvera
    module: vibe.algorithms.muvera
    name: muvera
    run_groups:
      base:
        args: [[2, 4, 6], [8, 16, 32], [5, 10, 20], [16, 32]]
        query_args: [[100, 200, 400, 800, 1600], [100, 200, 400, 800, 1600]]
