float:
  any:
  - base_args: ['@metric']
    constructor: Glass
    disabled: false
    singularity_image: glass
    module: vibe.algorithms.glass
    name: glass
    run_groups:
      glass:
        args: [[400], [8, 16, 32, 48, 64], [SQ8U], [SQ4U, SQ8U], [FP16, FP32]]
        query_args: [[10, 20, 30, 40, 50, 60, 80, 100, 150, 200, 300, 400, 500, 600, 800, 1000]]
