float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: Glass
    disabled: false
    singularity_image: glass
    module: vibe.algorithms.glass
    name: glass
    run_groups:
      HNSW:
        args:
          L: 200
          R: [8, 16, 32, 48, 64]
          level: [1, 2, 3]
        query_args: [[10, 20, 30, 40, 50, 60, 80, 100, 150, 200, 300, 400, 500, 600, 800, 1000]]
