binary:
  hamming:
  - base_args: ['@metric']
    constructor: Annoy
    disabled: true
    singularity_image: annoy
    module: vibe.algorithms.annoy
    name: annoy
    run_groups:
      annoy:
        args: [[50, 100, 200, 300, 400, 500]]
        query_args: [[100, 200, 400, 1000, 2000, 4000, 10000, 20000, 40000, 100000,
            200000, 400000]]
float:
  any:
  - base_args: ['@metric']
    constructor: Annoy
    disabled: false
    singularity_image: annoy
    module: vibe.algorithms.annoy
    name: annoy
    run_groups:
      annoy:
        args: [[50, 100, 200, 300, 400, 500]]
        query_args: [[100, 200, 400, 1000, 2000, 4000, 10000, 20000, 40000, 100000,
            200000, 400000]]
