uint8:
  euclidean:
  - base_args: ['@metric']
    constructor: Lorann
    disabled: false
    ood: true
    singularity_image: lorann
    module: vibe.algorithms.lorann
    name: lorann
    run_groups:
      lorann:
        args:
          quantization_bits: [8]
          n_clusters: [1024, 2048]
          global_dim: [96, 128, 192, 256, 384]
          rank: [32]
          train_size: [5]
        query_args:
        - - {clusters_to_search: 8, points_to_rerank: 100}
          - {clusters_to_search: 8, points_to_rerank: 200}
          - {clusters_to_search: 8, points_to_rerank: 400}
          - {clusters_to_search: 8, points_to_rerank: 800}
          - {clusters_to_search: 16, points_to_rerank: 100}
          - {clusters_to_search: 16, points_to_rerank: 200}
          - {clusters_to_search: 16, points_to_rerank: 400}
          - {clusters_to_search: 16, points_to_rerank: 800}
          - {clusters_to_search: 24, points_to_rerank: 400}
          - {clusters_to_search: 24, points_to_rerank: 800}
          - {clusters_to_search: 24, points_to_rerank: 1200}
          - {clusters_to_search: 24, points_to_rerank: 1600}
          - {clusters_to_search: 32, points_to_rerank: 400}
          - {clusters_to_search: 32, points_to_rerank: 800}
          - {clusters_to_search: 32, points_to_rerank: 1200}
          - {clusters_to_search: 32, points_to_rerank: 1600}
          - {clusters_to_search: 48, points_to_rerank: 800}
          - {clusters_to_search: 48, points_to_rerank: 1200}
          - {clusters_to_search: 48, points_to_rerank: 1600}
          - {clusters_to_search: 48, points_to_rerank: 2400}
          - {clusters_to_search: 64, points_to_rerank: 1200}
          - {clusters_to_search: 64, points_to_rerank: 1600}
          - {clusters_to_search: 64, points_to_rerank: 2400}
          - {clusters_to_search: 64, points_to_rerank: 3200}
          - {clusters_to_search: 128, points_to_rerank: 1200}
          - {clusters_to_search: 128, points_to_rerank: 1600}
          - {clusters_to_search: 128, points_to_rerank: 2400}
          - {clusters_to_search: 128, points_to_rerank: 3200}
          - {clusters_to_search: 256, points_to_rerank: 2400}
          - {clusters_to_search: 256, points_to_rerank: 3200}
          - {clusters_to_search: 256, points_to_rerank: 4000}
          - {clusters_to_search: 256, points_to_rerank: 4800}
float:
  any:
  - base_args: ['@metric']
    constructor: Lorann
    disabled: false
    ood: true
    singularity_image: lorann
    module: vibe.algorithms.lorann
    name: lorann
    run_groups:
      lorann:
        args:
          quantization_bits: [8]
          n_clusters: [1024, 2048]
          global_dim: [96, 128, 192, 256, 384]
          rank: [32]
          train_size: [5]
        query_args:
        - - {clusters_to_search: 8, points_to_rerank: 100}
          - {clusters_to_search: 8, points_to_rerank: 200}
          - {clusters_to_search: 8, points_to_rerank: 400}
          - {clusters_to_search: 8, points_to_rerank: 800}
          - {clusters_to_search: 16, points_to_rerank: 100}
          - {clusters_to_search: 16, points_to_rerank: 200}
          - {clusters_to_search: 16, points_to_rerank: 400}
          - {clusters_to_search: 16, points_to_rerank: 800}
          - {clusters_to_search: 24, points_to_rerank: 400}
          - {clusters_to_search: 24, points_to_rerank: 800}
          - {clusters_to_search: 24, points_to_rerank: 1200}
          - {clusters_to_search: 24, points_to_rerank: 1600}
          - {clusters_to_search: 32, points_to_rerank: 400}
          - {clusters_to_search: 32, points_to_rerank: 800}
          - {clusters_to_search: 32, points_to_rerank: 1200}
          - {clusters_to_search: 32, points_to_rerank: 1600}
          - {clusters_to_search: 48, points_to_rerank: 800}
          - {clusters_to_search: 48, points_to_rerank: 1200}
          - {clusters_to_search: 48, points_to_rerank: 1600}
          - {clusters_to_search: 48, points_to_rerank: 2400}
          - {clusters_to_search: 64, points_to_rerank: 1200}
          - {clusters_to_search: 64, points_to_rerank: 1600}
          - {clusters_to_search: 64, points_to_rerank: 2400}
          - {clusters_to_search: 64, points_to_rerank: 3200}
          - {clusters_to_search: 128, points_to_rerank: 1200}
          - {clusters_to_search: 128, points_to_rerank: 1600}
          - {clusters_to_search: 128, points_to_rerank: 2400}
          - {clusters_to_search: 128, points_to_rerank: 3200}
          - {clusters_to_search: 256, points_to_rerank: 2400}
          - {clusters_to_search: 256, points_to_rerank: 3200}
          - {clusters_to_search: 256, points_to_rerank: 4000}
          - {clusters_to_search: 256, points_to_rerank: 4800}
