project:
  type: website

website:
  title: "VIBE: Vector Index Benchmark for Embeddings"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Overview"
        href: overview.qmd
      - text: "Datasets"
        href: datasets.qmd
      - text: "Tradeoffs"
        href: tradeoff.qmd
      - text: "Algorithm focus"
        href: algorithm_focus.qmd


format:
  html:
    toc: false
    theme: flatly

